### ISSUE TITLE
Error report for primeaio 0.5.1

### ISSUE THREAD

**Issue by Marhvin** [Nisthar/primeaio-issues#1]
Error:
```TypeError: Cannot read property 'webContents' of undefined
    at m.<anonymous> (evalmachine.<anonymous>:1:2826162)
    at m.emit (events.js:315:20)
    at m.doCheckForUpdates (evalmachine.<anonymous>:1:339948)
    at m.checkForUpdates (evalmachine.<anonymous>:1:337436)
    at m.checkForUpdatesAndNotify (evalmachine.<anonymous>:1:337803)
    at Timeout._onTimeout (evalmachine.<anonymous>:1:2822179)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```
OS: Windows NT 10.0.18363

**Comment by Nisthar** [comment]
Try the latest version
