### ISSUE TITLE
Error report for primeaio 0.5.7

### ISSUE THREAD

**Issue by winson6969** [Nisthar/primeaio-issues#2]
Error:
```Error: listen EADDRINUSE: address already in use :::5001
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1447:7)
    at Function.listen (C:\Program Files\primeaio\resources\app.asar\node_modules\express\lib\application.js:618:24)
    at evalmachine.<anonymous>:1:2830373
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async App.<anonymous> (evalmachine.<anonymous>:1:2828212)
```
OS: Windows NT 10.0.18363

**Comment by Nisthar** [comment]
Seems related to your pc. 

When do you get the error?
